version: 1.0.{build}

platform:
  - x64

install:
  - cmd: echo "Downloading conan..."
  - cmd: set QTDIR=C:\Qt\5.11.1\msvc2015_64\
  - cmd: set PATH=%PATH%;%PYTHON%/Scripts/;%QTDIR%\bin
  - cmd: pip.exe install conan
  - cmd: conan user # Create the conan data directory
  - cmd: conan --version
  - cmd: conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan

build_script:
  - cmd: mkdir build
  - cmd: conan install . -g qmake
  - cmd: cd build
  - cmd: echo %QTDIR%
  - cmd: dir %QTDIR%
  - cmd: qmake ../ -G "Visual Studio 14 2015 Win64"
  - cmd: qmake_all

test_script:
  - cmd: dir
