version: 1.0.{build}

platform:
  - x64

install:
  - cmd: echo "Downloading conan..."
  - cmd: pip.exe install conan
  - cmd: conan user # Create the conan data directory
  - cmd: conan --version
  - cmd: conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan

build_script:
  - cmd: conan install . -g qmake -g virtualenv
  - cmd: activate.bat && SET
  - cmd: qtenv2.bat
  - cmd: vcvarsall.bat
  - cmd: qmake -platform win32-msvc ModbusScope.pro
  - cmd: qmake_all

test_script:
  - cmd: dir
