version: 1.0.{build}

platform:
  - x64

install:
  - cmd: echo "Downloading conan..."
  - cmd: set PATH=%PATH%;%PYTHON%/Scripts/
  - cmd: pip.exe install conan
  - cmd: conan user # Create the conan data directory
  - cmd: conan --version
  - cmd: conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan

build_script:
  - cmd: mkdir build
  - cmd: conan install . -g qmake
  - cmd: set PATH=%PATH%;%QTDIR%\bin
  - cmd: cd build
  - cmd: dir %QTDIR%
  - cmd: dir %QTDIR%\bin
  - cmd: %QTDIR%\bin\qmake ../ -DBUILD_TEST=TRUE  -G "Visual Studio 14 2015 Win64"

test_script:
  - cmd: dir
