version: 1.0.{build}

platform:
  - x64

cache:
 - C:\Users\Appveyor\.conan -> conanfile.txt 
 - C:\.conan -> conanfile.txt

install:
  - cmd: echo "Downloading conan..."
  - cmd: pip.exe install conan
  - cmd: conan user # Create the conan data directory
  - cmd: conan --version
  - cmd: conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan || exit 0
  - cmd: set PATH=C:\MinGW\bin;%PATH%
  - cmd: echo %PATH%
  
build_script:
  - cmd: mkdir build
  - cmd: cd build
  - cmd: conan install .. -g virtualenv -s os=Windows -s compiler=gcc -s compiler.version=5.3 -s compiler.libcxx=libstdc++11
  - cmd: activate.bat
  - cmd: SET QTDIR=%CMAKE_PREFIX_PATH:;=%
  - cmd: SET QMAKESPEC=win32-g++
  - cmd: qmake --version
  - ps: cat conanbuildinfo.txt
  - ps: cat conaninfo.txt
  - ps: cat activate.bat
  - cmd: echo %QTDIR%
  - cmd: qmake ..\ModbusScope.pro
  - cmd: mingw32-make -j2

artifacts:
 - path: build\src\release\ModbusScope.exe

