version: 1.0.{build}

platform:
  - x64

cache:
 - C:\Users\Appveyor\.conan -> conanfile.txt 
 - C:\.conan -> conanfile.txt

install:
  - cmd: echo "Downloading conan..."
  - cmd: pip.exe install conan
  - cmd: conan user # Create the conan data directory
  - cmd: conan --version
  - cmd: conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan

build_script:
  - cmd: conan install . -g qmake -g virtualenv
  - cmd: activate.bat && SET
  - cmd: dir %CMAKE_PREFIX_PATH%
  - cmd: dir %CMAKE_PREFIX_PATH%\bin
  - cmd: ECHO '%CMAKE_PREFIX_PATH%\bin\qtenv2.bat'
  - cmd: '%CMAKE_PREFIX_PATH%\bin\qtenv2.bat'
  - cmd: qmake --version
  - cmd: where qmake
  - cmd: qmake -d -d -d -spec %CMAKE_PREFIX_PATH%\\mkspecs\\win32-msvc ModbusScope.pro
  - cmd: qmake_all

test_script:
  - cmd: dir
