version: 1.0.{build}
    platform:
      - x64

    install:
      - cmmd: echo "Downloading conan..."
      - cmmd: set PATH=%PATH%;%PYTHON%/Scripts/
      - cmmd: pip.exe install conan
      - cmmd: conan user # Create the conan data directory
      - cmmd: conan --version

    build_script:
      - cmmd: mkdir build
      - cmmd: conan install . -g qmake
      - cmmd: cd build
      - cmmd: qmake ../ -DBUILD_TEST=TRUE  -G "Visual Studio 14 2015 Win64"

    test_script:
      - cmmd: dir
