version: 1.0.{build}

platform:
  - x64

install:
  - cmd: echo "Downloading conan..."
  - cmd: set PATH=%PATH%;%PYTHON%/Scripts/
  - cmd: pip.exe install conan
  - cmd: conan user # Create the conan data directory
  - cmd: conan --version

build_script:
  - cmd: mkdir build
  - cmd: conan install . -g qmake
  - cmd: cd build
  - cmd: qmake ../ -DBUILD_TEST=TRUE  -G "Visual Studio 14 2015 Win64"

test_script:
  - cmd: dir
